#!/bin/bash

echo "🧹 [CLEANUP] TACTICAL MESH DOCKER RESET"
echo "----------------------------------------"

# 1. DOCKER CONTAINER NUKE
# Finds any container with "tactical" in the name (e.g., tactical-unit-01, tactical-test-unit)
echo "🐳 Hunting Tactical Containers..."
CONTAINERS=$(docker ps -aq --filter name=tactical)

if [ -n "$CONTAINERS" ]; then
    count=$(echo "$CONTAINERS" | wc -l | xargs)
    echo "   Found $count active units. TERMINATING..."
    # Force remove (-f) stops and deletes them instantly
    docker rm -f $CONTAINERS > /dev/null
    echo "   ✅ Containers Destroyed."
else
    echo "   ✅ No active units found."
fi

# 2. DOCKER NETWORK CLEANUP
# Removes the private bridge network used in wargames
echo "🌐 Scrubbing Networks..."
if docker network ls | grep -q "tactical-net"; then
    docker network rm tactical-net > /dev/null
    echo "   ✅ Network 'tactical-net' removed."
else
    echo "   ✅ Network clean."
fi

# 3. LOCAL ARTIFACT CLEANUP
# We still clean these because they are mounted as volumes into the containers
echo "🗑️  Scrubbing filesystem..."

# Remove key directories generated by provisioning scripts
rm -rf ./keys
rm -rf ./keys_test
rm -rf ./keys_wargame
echo "   - Deleted Key Volumes (keys/, keys_test/, keys_wargame/)"

# Remove any stray DBs if you ran local tests
rm -rf ./test_db_*
echo "   - Deleted Local RocksDB Artifacts"

# Remove Python Cache
find . -type d -name "__pycache__" -exec rm -rf {} +
echo "   - Cleared __pycache__"

echo "----------------------------------------"
echo "✅ BATTLEFIELD CLEARED."