
# --- NETWORK ---
BASE_PORT = 9000 

LANE_FLASH = 0   
LANE_ROUTINE = 1 
LANE_BULK = 2    

GOSSIP_INTERVAL = 0.2      
BEACON_INTERVAL = 1.0      
ZMQ_HWM = 10000            
ZMQ_RCV_TIMEOUT = 600     

# --- SECURITY ---
CURVE_ENABLED = True

DB_WRITE_BUFFER = 64 * 1024 * 1024  
COMPRESSION = "lz4"        

TRAFFIC_WRITE_INTERVAL = 0.1  
TEST_CONVERGENCE_TIMEOUT = 30