// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TACTICAL_TACTICAL_H_
#define FLATBUFFERS_GENERATED_TACTICAL_TACTICAL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Tactical {

struct VectorClockEntry;
struct VectorClockEntryBuilder;

struct Update;
struct UpdateBuilder;

struct Heartbeat;
struct HeartbeatBuilder;

struct SyncReq;
struct SyncReqBuilder;

struct Message;
struct MessageBuilder;

enum Payload : uint8_t {
  Payload_NONE = 0,
  Payload_Update = 1,
  Payload_Heartbeat = 2,
  Payload_SyncReq = 3,
  Payload_MIN = Payload_NONE,
  Payload_MAX = Payload_SyncReq
};

inline const Payload (&EnumValuesPayload())[4] {
  static const Payload values[] = {
    Payload_NONE,
    Payload_Update,
    Payload_Heartbeat,
    Payload_SyncReq
  };
  return values;
}

inline const char * const *EnumNamesPayload() {
  static const char * const names[5] = {
    "NONE",
    "Update",
    "Heartbeat",
    "SyncReq",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayload(Payload e) {
  if (::flatbuffers::IsOutRange(e, Payload_NONE, Payload_SyncReq)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayload()[index];
}

template<typename T> struct PayloadTraits {
  static const Payload enum_value = Payload_NONE;
};

template<> struct PayloadTraits<Tactical::Update> {
  static const Payload enum_value = Payload_Update;
};

template<> struct PayloadTraits<Tactical::Heartbeat> {
  static const Payload enum_value = Payload_Heartbeat;
};

template<> struct PayloadTraits<Tactical::SyncReq> {
  static const Payload enum_value = Payload_SyncReq;
};

template <bool B = false>
bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type);
template <bool B = false>
bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct VectorClockEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VectorClockEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODE_ID = 4,
    VT_SEQ = 6
  };
  const ::flatbuffers::String *node_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NODE_ID);
  }
  uint64_t seq() const {
    return GetField<uint64_t>(VT_SEQ, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODE_ID) &&
           verifier.VerifyString(node_id()) &&
           VerifyField<uint64_t>(verifier, VT_SEQ, 8) &&
           verifier.EndTable();
  }
};

struct VectorClockEntryBuilder {
  typedef VectorClockEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_node_id(::flatbuffers::Offset<::flatbuffers::String> node_id) {
    fbb_.AddOffset(VectorClockEntry::VT_NODE_ID, node_id);
  }
  void add_seq(uint64_t seq) {
    fbb_.AddElement<uint64_t>(VectorClockEntry::VT_SEQ, seq, 0);
  }
  explicit VectorClockEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VectorClockEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VectorClockEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VectorClockEntry> CreateVectorClockEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> node_id = 0,
    uint64_t seq = 0) {
  VectorClockEntryBuilder builder_(_fbb);
  builder_.add_seq(seq);
  builder_.add_node_id(node_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VectorClockEntry> CreateVectorClockEntryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *node_id = nullptr,
    uint64_t seq = 0) {
  auto node_id__ = node_id ? _fbb.CreateString(node_id) : 0;
  return Tactical::CreateVectorClockEntry(
      _fbb,
      node_id__,
      seq);
}

struct Update FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_S = 4,
    VT_P = 6,
    VT_O = 8,
    VT_CLOCK = 10,
    VT_SOURCE = 12
  };
  const ::flatbuffers::String *s() const {
    return GetPointer<const ::flatbuffers::String *>(VT_S);
  }
  const ::flatbuffers::String *p() const {
    return GetPointer<const ::flatbuffers::String *>(VT_P);
  }
  const ::flatbuffers::String *o() const {
    return GetPointer<const ::flatbuffers::String *>(VT_O);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Tactical::VectorClockEntry>> *clock() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Tactical::VectorClockEntry>> *>(VT_CLOCK);
  }
  const ::flatbuffers::String *source() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SOURCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_S) &&
           verifier.VerifyString(s()) &&
           VerifyOffset(verifier, VT_P) &&
           verifier.VerifyString(p()) &&
           VerifyOffset(verifier, VT_O) &&
           verifier.VerifyString(o()) &&
           VerifyOffset(verifier, VT_CLOCK) &&
           verifier.VerifyVector(clock()) &&
           verifier.VerifyVectorOfTables(clock()) &&
           VerifyOffset(verifier, VT_SOURCE) &&
           verifier.VerifyString(source()) &&
           verifier.EndTable();
  }
};

struct UpdateBuilder {
  typedef Update Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_s(::flatbuffers::Offset<::flatbuffers::String> s) {
    fbb_.AddOffset(Update::VT_S, s);
  }
  void add_p(::flatbuffers::Offset<::flatbuffers::String> p) {
    fbb_.AddOffset(Update::VT_P, p);
  }
  void add_o(::flatbuffers::Offset<::flatbuffers::String> o) {
    fbb_.AddOffset(Update::VT_O, o);
  }
  void add_clock(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Tactical::VectorClockEntry>>> clock) {
    fbb_.AddOffset(Update::VT_CLOCK, clock);
  }
  void add_source(::flatbuffers::Offset<::flatbuffers::String> source) {
    fbb_.AddOffset(Update::VT_SOURCE, source);
  }
  explicit UpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Update> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Update>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Update> CreateUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> s = 0,
    ::flatbuffers::Offset<::flatbuffers::String> p = 0,
    ::flatbuffers::Offset<::flatbuffers::String> o = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Tactical::VectorClockEntry>>> clock = 0,
    ::flatbuffers::Offset<::flatbuffers::String> source = 0) {
  UpdateBuilder builder_(_fbb);
  builder_.add_source(source);
  builder_.add_clock(clock);
  builder_.add_o(o);
  builder_.add_p(p);
  builder_.add_s(s);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Update> CreateUpdateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *s = nullptr,
    const char *p = nullptr,
    const char *o = nullptr,
    const std::vector<::flatbuffers::Offset<Tactical::VectorClockEntry>> *clock = nullptr,
    const char *source = nullptr) {
  auto s__ = s ? _fbb.CreateString(s) : 0;
  auto p__ = p ? _fbb.CreateString(p) : 0;
  auto o__ = o ? _fbb.CreateString(o) : 0;
  auto clock__ = clock ? _fbb.CreateVector<::flatbuffers::Offset<Tactical::VectorClockEntry>>(*clock) : 0;
  auto source__ = source ? _fbb.CreateString(source) : 0;
  return Tactical::CreateUpdate(
      _fbb,
      s__,
      p__,
      o__,
      clock__,
      source__);
}

struct Heartbeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartbeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NODE_ID = 4,
    VT_PORT = 6
  };
  const ::flatbuffers::String *node_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NODE_ID);
  }
  uint16_t port() const {
    return GetField<uint16_t>(VT_PORT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NODE_ID) &&
           verifier.VerifyString(node_id()) &&
           VerifyField<uint16_t>(verifier, VT_PORT, 2) &&
           verifier.EndTable();
  }
};

struct HeartbeatBuilder {
  typedef Heartbeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_node_id(::flatbuffers::Offset<::flatbuffers::String> node_id) {
    fbb_.AddOffset(Heartbeat::VT_NODE_ID, node_id);
  }
  void add_port(uint16_t port) {
    fbb_.AddElement<uint16_t>(Heartbeat::VT_PORT, port, 0);
  }
  explicit HeartbeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Heartbeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Heartbeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> node_id = 0,
    uint16_t port = 0) {
  HeartbeatBuilder builder_(_fbb);
  builder_.add_node_id(node_id);
  builder_.add_port(port);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Heartbeat> CreateHeartbeatDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *node_id = nullptr,
    uint16_t port = 0) {
  auto node_id__ = node_id ? _fbb.CreateString(node_id) : 0;
  return Tactical::CreateHeartbeat(
      _fbb,
      node_id__,
      port);
}

struct SyncReq FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SyncReqBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LAST_SEQ = 4
  };
  uint64_t last_seq() const {
    return GetField<uint64_t>(VT_LAST_SEQ, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_LAST_SEQ, 8) &&
           verifier.EndTable();
  }
};

struct SyncReqBuilder {
  typedef SyncReq Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_last_seq(uint64_t last_seq) {
    fbb_.AddElement<uint64_t>(SyncReq::VT_LAST_SEQ, last_seq, 0);
  }
  explicit SyncReqBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SyncReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SyncReq>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SyncReq> CreateSyncReq(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t last_seq = 0) {
  SyncReqBuilder builder_(_fbb);
  builder_.add_last_seq(last_seq);
  return builder_.Finish();
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE_TYPE = 4,
    VT_TYPE = 6
  };
  Tactical::Payload type_type() const {
    return static_cast<Tactical::Payload>(GetField<uint8_t>(VT_TYPE_TYPE, 0));
  }
  const void *type() const {
    return GetPointer<const void *>(VT_TYPE);
  }
  template<typename T> const T *type_as() const;
  const Tactical::Update *type_as_Update() const {
    return type_type() == Tactical::Payload_Update ? static_cast<const Tactical::Update *>(type()) : nullptr;
  }
  const Tactical::Heartbeat *type_as_Heartbeat() const {
    return type_type() == Tactical::Payload_Heartbeat ? static_cast<const Tactical::Heartbeat *>(type()) : nullptr;
  }
  const Tactical::SyncReq *type_as_SyncReq() const {
    return type_type() == Tactical::Payload_SyncReq ? static_cast<const Tactical::SyncReq *>(type()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE_TYPE, 1) &&
           VerifyOffset(verifier, VT_TYPE) &&
           VerifyPayload(verifier, type(), type_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Tactical::Update *Message::type_as<Tactical::Update>() const {
  return type_as_Update();
}

template<> inline const Tactical::Heartbeat *Message::type_as<Tactical::Heartbeat>() const {
  return type_as_Heartbeat();
}

template<> inline const Tactical::SyncReq *Message::type_as<Tactical::SyncReq>() const {
  return type_as_SyncReq();
}

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type_type(Tactical::Payload type_type) {
    fbb_.AddElement<uint8_t>(Message::VT_TYPE_TYPE, static_cast<uint8_t>(type_type), 0);
  }
  void add_type(::flatbuffers::Offset<void> type) {
    fbb_.AddOffset(Message::VT_TYPE, type);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Tactical::Payload type_type = Tactical::Payload_NONE,
    ::flatbuffers::Offset<void> type = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_type(type);
  builder_.add_type_type(type_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type) {
  switch (type) {
    case Payload_NONE: {
      return true;
    }
    case Payload_Update: {
      auto ptr = reinterpret_cast<const Tactical::Update *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Heartbeat: {
      auto ptr = reinterpret_cast<const Tactical::Heartbeat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_SyncReq: {
      auto ptr = reinterpret_cast<const Tactical::SyncReq *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayload(
        verifier,  values->Get(i), types->GetEnum<Payload>(i))) {
      return false;
    }
  }
  return true;
}

inline const Tactical::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<Tactical::Message>(buf);
}

inline const Tactical::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Tactical::Message>(buf);
}

template <bool B = false>
inline bool VerifyMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<Tactical::Message>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<Tactical::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tactical::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Tactical::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Tactical

#endif  // FLATBUFFERS_GENERATED_TACTICAL_TACTICAL_H_
