import streamlit as st
import docker
import networkx as nx
import matplotlib.pyplot as plt
import time
import json
import os
import sys
import pandas as pd

# Add Project Root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from src.mission_clock import STATE_FILE

# --- CONFIG ---
st.set_page_config(page_title="ZENITH CONVERGENCE HUD", page_icon="📡", layout="wide")
st.markdown("""
    <style>
    .stApp { background-color: #0e1117; }
    .metric-card { background-color: #1c1f26; padding: 15px; border-radius: 8px; border-left: 5px solid #00ff00; }
    .diverged { border-left: 5px solid #ff0000; }
    .lagging { border-left: 5px solid #ffcc00; }
    </style>
""", unsafe_allow_html=True)

try:
    client = docker.from_env()
except:
    st.error("DOCKER OFFLINE")
    st.stop()

# --- DATA FETCHING ---
def get_node_status(container):
    """
    Executes a cat command inside the container to read the status file.
    This bypasses DB locks.
    """
    try:
        # We read the JSON file generated by GossipNode.dump_status()
        exit_code, output = container.exec_run("cat /data/node_status.json")
        if exit_code == 0:
            return json.loads(output.decode())
    except:
        pass
    return None

def get_mission_state():
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, "r") as f: return json.load(f)
        except: pass
    return {"phase": "OFFLINE", "status": "..."}

# --- MAIN UI ---
state = get_mission_state()
phase = state.get("phase", "UNKNOWN")

st.title(f"📡 TACTICAL MESH: {phase}")
st.caption(f"Status: {state.get('status')} | Threat: {'ACTIVE' if state.get('active_rogue') else 'NONE'}")

# 1. GATHER DATA
containers = client.containers.list(all=True)
tactical_nodes = [c for c in containers if "tactical-" in c.name]
node_data = []

for c in tactical_nodes:
    if c.status == "running":
        status = get_node_status(c)
        if status:
            node_data.append(status)
        else:
            # Fallback if file not yet written
            node_data.append({"node_id": c.name, "vector_clock": {}, "timestamp": 0})

# 2. CALCULATE CONVERGENCE
if node_data:
    # Flatten Vector Clocks for Dataframe
    # We want a table: [Node ID] | [Unit_00 Clock] | [Unit_01 Clock] ...
    
    df_rows = []
    all_clock_keys = set()
    
    for n in node_data:
        vc = n.get("vector_clock", {})
        row = {"Node": n["node_id"], "Last Update": time.strftime('%H:%M:%S', time.localtime(n["timestamp"]))}
        for k, v in vc.items():
            row[k] = v
            all_clock_keys.add(k)
        df_rows.append(row)
    
    df = pd.DataFrame(df_rows).set_index("Node")
    
    # Fill NaN with 0 (missing knowledge)
    df = df.fillna(0)
    
    # 3. VISUALIZATION
    col_grid, col_matrix = st.columns([1, 2])
    
    with col_grid:
        st.subheader("Mesh Health")
        # Check if all rows are identical (Full Convergence)
        # We drop 'Last Update' for comparison
        compare_df = df.drop(columns=["Last Update"], errors='ignore')
        
        is_converged = False
        if not compare_df.empty:
            # Check if all rows are duplicates of the first row
            is_converged = (compare_df.nunique() <= 1).all()
        
        if is_converged:
            st.success("✅ MESH CONVERGED")
            st.metric("Global State", "SYNCED")
        else:
            st.warning("⚠️ DIVERGENCE DETECTED")
            st.metric("Global State", "SYNCING...")

        # Display Network Graph
        G = nx.Graph()
        for n in node_data:
            G.add_node(n["node_id"], color="#00ff00" if is_converged else "#ffcc00")
            # Connect everyone (Mesh)
            for other in node_data:
                if n["node_id"] != other["node_id"]:
                    G.add_edge(n["node_id"], other["node_id"])
                    
        if not G.nodes:
            st.info("No Data")
        else:
            pos = nx.circular_layout(G)
            fig, ax = plt.subplots(figsize=(4, 4))
            fig.patch.set_facecolor('#0e1117')
            ax.set_facecolor('#0e1117')
            nx.draw(G, pos, node_color="#00ff00" if is_converged else "#ffcc00", node_size=500, with_labels=True, font_color="white", ax=ax)
            st.pyplot(fig)

    with col_matrix:
        st.subheader("Live Vector Clock Matrix")
        st.caption("Rows = Nodes | Cols = Knowledge of Peer Versions")
        
        # Highlight Logic
        def highlight_max(s):
            is_max = s == s.max()
            return ['background-color: #1f77b4' if v else '' for v in is_max]

        # Display the Matrix
        if not df.empty:
            st.dataframe(
                df.style.apply(highlight_max, subset=list(all_clock_keys)),
                use_container_width=True,
                height=300
            )
            
            st.markdown("---")
            st.markdown("**Convergence Logic:**")
            
            st.text("If all cells in a column match, every node agrees on the state of that peer.")
            st.text("If a cell is lower, that node is missing updates.")

else:
    st.info("Waiting for telemetry...")

time.sleep(1)
st.rerun()